name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  common:
    # uses: City-of-Helsinki/.github/.github/workflows/ci-dotnet.yml@main
    uses: City-of-Helsinki/.github/.github/workflows/ci-dotnet.yml@dotnet_PLATTA-7760
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
